In [2]:
import numpy as np

In [3]:
A = np.array([[3, 6, 3],
              [2, 4, 2],
              [1, 2, 1]])

In [4]:
print(f'Rank of X: {np.linalg.matrix_rank(A)}')

Rank of X: 1


In [6]:
Y = np.array([[5, None,   7],
              [None, 2, None],
              [4, None, None],
              [None, 3, 6],])

[[5 None 7]
 [None 2 None]
 [4 None None]
 [None 3 6]]


In [9]:
U, V = [], []

In [10]:
U.append(np.array([[6, 0, 3, 6]]))
V.append(np.array([[4,2,1]]))

In [11]:
def get_X(U, V):
    """
    Gets the matrix X = U * V_T
    
    Input:
    U - Column vector for the estimated matrix X
    V - Row vector for the estimated matrix X
    
    Output:
    X - matrix estimation of Y
    """
    return np.transpose(U) * V

def square_error(Y, X):
    """
    Return the square error between the estimation and the real value of Y
    
    returns: 1/2 * sum(Yai - Xai)^2
    
    Input:
    Y - real matrix
    X - estimated matrix
    """
    n_row, n_col, temp = Y.shape[0], Y.shape[1], 0
    for i in range(n_row):
        for j in range(n_col):
            if Y[i][j]:
                temp += (Y[i][j] - X[i][j])**2
            
    return temp/2

def square_sum(X):
    """
    Returns the sum of the square of each elements of a vector.
    
    Input: 
    X - matrix like
    Output:
    Scalar
    """
    n_row, n_col, temp = X.shape[0], X.shape[1], 0
    for i in range(n_row):
        for j in range(n_col):
            temp += X[i][j]**2
    
    return temp

def regularization(L, U, V):
    return L/2*(square_sum(U) + square_sum(V))

In [16]:
def main():
    X = get_X(U[0], V[0])
    squared_error = square_error(Y, X)
    reg = regularization(1, U[0], V[0])
    
    print(f'Empirical Error: {squared_error}')
    print(f'Regularization: {reg}')
    
if __name__=="__main__":
    main()

Empirical Error: 255.5
Regularization: 51.0


In [17]:
Y

array([[5, None, 7],
       [None, 2, None],
       [4, None, None],
       [None, 3, 6]], dtype=object)

In [22]:
V[0]

array([[4, 2, 1]])

In [24]:
U[1] = np.array([[a, b, c, d]])

NameError: name 'a' is not defined

In [26]:
from scipy.optimize import fsolve

In [27]:
def func(x):
    return [x[0] * np.cos(x[1]) - 4, x[1] * x[0] - x[1] - 5]

root = fsolve(func, [1,1])
print(f'Roots: {root}')

Roots: [6.50409711 0.90841421]


In [28]:
def estim(Y, U, V):
    L = 1
    V = np.transpose(V)
    n_row, n_col = Y.shape
    M = np.zeros((n_row, n_col))
    
    X = U*V
    
    for i in range(n_row):
        for j in range(n_col):
            if Y[i][j]:
                M[i][j] = -V[j] * (Y[i][j] - X[i][j]) + L * X[i][j]
                
    return M

V = np.array([[4,2,1]])

In [31]:
V = np.transpose(V)

In [43]:
n, m = 2, 6
A = np.zeros((n, m))

In [44]:
A

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [45]:
for i in range(n):
    for j in range(m):
        if n == 1:
            A[i][j] = 1/6
            
        else:
            if m < 4:
                A[i][j] = 1/3
            else:
                A[i][j] - -1/3
        

In [48]:
for j in range(m):
    A[0][j] = 1/6
    
for j in range(m):
    if j<3:
        A[1][j] = 1/3
    else:
        A[1][j] = -1/3

In [51]:
np.around(A, decimals=4, out=None)

array([[ 0.1667,  0.1667,  0.1667,  0.1667,  0.1667,  0.1667],
       [ 0.3333,  0.3333,  0.3333, -0.3333, -0.3333, -0.3333]])